[package]
name = "librustbiome"
version = "0.1.0"
authors = ["toddernst"]
edition = "2018"
include = ["src/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8", features = ["macros"] }
packed_simd = "0.3.3"